---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  # encryption - establish wireguard tunnels for inter-node traffic (intra-node traffic is not encrypted)
  # kubeProxyReplacement - use eBPF instead of kube-proxy and iptables
  #   - k8sServiceHost and k8sServicePort must be set to the API server address and port
  #   - wireguard tunnel endpoint is exposed on UDP 51871 port
  # localRedirectPolicy - route DNS traffic to NodeLocal DNSCache
  # hubble - enable Hubble UI for network observability
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    localRedirectPolicy: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
